name: Build master - $(Build.BuildId)

# trigger:
#   branches:
#     include:
#     - master

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml

  # - job: Windows
  #   pool:
  #     vmImage: windows-latest
  #   variables:
  #     ESY__PREFIX: $(Pipeline.Workspace)\.esy
  #   steps:
  #   - template: .ci/build-platform.yml
  #     parameters:
  #       esyLockPath: $(Build.SourcesDirectory)\esy.lock\index.json
  #       installFolderPath: \3_

- stage: Build_NPM
  displayName: Build NPM packages
  dependsOn: [build]
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: .ci/create-npm-package.yml
      parameters:
        package_name: $(package_name)
